### ISSUE TITLE
Lens 1.0 Checklist

### ISSUE THREAD

**Issue by jackzampolin** [strangelove-ventures/lens#99]
The following is a list of features I would like to see before `lens` (both client and CLI application) hit 1.0:
- [ ] Integration of the dynamic cosmos work https://github.com/fdymylja/dynamic-cosmos
    * [ ] Storage of the proto definitions for each chain in the `~/.lens/{chain-id}/proto/` dir or in the case of `client` have a couple of other backends (interface to support in memory, file, or db)
    * [ ] To be defined API for queries. I have a 
- [ ] Creation of new keyserver for transaction signing (https://github.com/strangelove-ventures/lens/pull/95#issuecomment-1037269002)
- [ ] Completion of `authz` work to better integrate soft keys. This requires include a way for users to sign the authorization transactions to `lens` managed key from a ledger. We may have to hack this together.

**Comment by andynog** [comment]
Thanks, this gives some clarification on what needs to be done. Maybe we should break down those items into their own issues to provide more details on each and keep this as the master list. 

I'd like to help with the authz and ledger one.

**Comment by jackzampolin** [comment]
@andynog we should grab some time later this week to discuss the authz ledger integration and we can break the work down into some specific deliverables.
